# Метод Гаусса с частичным выбором ведущего элемента

#### Импорт модулей

In [17]:
import numpy as np        # для работы с матрицами и веторами
from typing import Union  # для работы с типизацией

#### Входные данные

In [18]:
A = np.matrix([[1.00, 0.17, -0.25, 0.54],
               [0.47, 1.00, 0.67, -0.32],
               [-0.11, 0.35, 1.00, -0.74],
               [0.55, 0.43, 0.36, 1.00]],
               dtype=np.dtype(np.float64))

In [19]:
f = np.array([0.3, 0.5, 0.7, 0.9],
             dtype=np.dtype(np.float64))

#### Тестовые наборы данных

In [20]:
test_A1 = np.matrix([[10., -7., 0.],
                    [-3., 2., 6.],
                    [5., -1., 5.]],
                    dtype=np.dtype(np.float64))

test_f1 = np.array([7, 4, 6],
                  dtype=np.dtype(np.float64))

In [21]:
test_A2 = np.matrix([[1., 2.],
                     [3., 4.]],
                     dtype=np.dtype(np.float64))

test_f2 = np.matrix([[3., 5.],
                     [5., 9.]],
                     dtype=np.dtype(np.float64))

In [22]:
test_A3 = np.matrix([[1., 2., 3.],
                     [4., 5., 6.],
                     [1., 0., 1.]],
                     dtype=np.dtype(np.float64))

test_f3 = np.array([1., 1., 1.],
                   dtype=np.dtype(np.float64))

In [23]:
test_A3 = np.matrix([[1., 1., 2., 3.],
                     [1., 2., 3., -1.],
                     [3., -1., -1., -2.],
                     [2., 3., -1., -1.]],
                     dtype=np.dtype(np.float64))

test_f3 = np.array([1, -4, -4, -6],
                   dtype=np.dtype(np.float64))

In [24]:
test_A4 = np.matrix([[1., -2., -1.],
                     [-3., 2., 2.],
                     [3., -1., -2.]],
                     dtype=np.dtype(np.float64))

test_f4 = np.matrix([[1., 0.],
                     [2., -2.],
                     [-3., 1.]],
                     dtype=np.dtype(np.float64))

*Устраняем проблему с мантиссой при выводе на экран*

In [25]:
np.set_printoptions(suppress=True)

### Алгоритм

In [26]:
def gaussian_elimination(A_arg: np.matrix, f_arg: Union[np.matrix, np.array]) -> Union[np.matrix, np.array]:
    A, f = np.copy(A_arg), np.copy(f_arg)
    print(f"Исходные данные:\n A:\n {A}\n\n f:\n{f}\n\n")
    for i in range(0, len(A)-1):
        column = np.abs(A[i:, i])  # берём i-ую колонку
        leading_elem = np.max(column)  # методом частичного выбора находим ведущий элемент
        if np.where(column == leading_elem)[0][0] != 0:  # нужно ли нам менять строки (?)
            pos_max = column.argmax() + i      # узнаём номер строки ведущего элемента
            A[[i, pos_max]] = A[[pos_max, i]]  # меняем строки местами в матрице коэф.
            f[[i, pos_max]] = f[[pos_max, i]]  # меняем строки местами в матрице ответ
        for j in range(i+1, len(A)):  # делаем верхний треугольник
            coef = -(A[j, i]/A[i, i]) # считаем коэффициент
            A[j] = coef * A[i] + A[j] # домножаем `i` строку и прибавляем `j`
            f[j] = coef * f[i] + f[j]
        print(f"{i+1} итерация:\n A:\n {A}\n\n f:\n{f}\n\n")

    n = f.shape[0]  # размерность нашего ответа
    X = np.zeros(shape=f.shape)   # заполняем наше будущее решение нулями
    X[n-1] = f[n-1]/A[n-1, n-1]   # решаем последнее уравнение
    for i in range(n-2, -1, -1):  # рассчитывает значения начиная с конца
        sum_elem = sum(A[i, j] * X[j] for j in range(i+1, n))  # для известных `x` суммируем коэффициенты
        X[i] = (f[i] - sum_elem)/A[i, i]
    print(f"Ответ:\n {X}")
    return X

#### Тесты

In [27]:
np.testing.assert_allclose(np.linalg.solve(A, f),
                           gaussian_elimination(A, f))

Исходные данные:
 A:
 [[ 1.    0.17 -0.25  0.54]
 [ 0.47  1.    0.67 -0.32]
 [-0.11  0.35  1.   -0.74]
 [ 0.55  0.43  0.36  1.  ]]

 f:
[0.3 0.5 0.7 0.9]


1 итерация:
 A:
 [[ 1.      0.17   -0.25    0.54  ]
 [ 0.      0.9201  0.7875 -0.5738]
 [ 0.      0.3687  0.9725 -0.6806]
 [ 0.      0.3365  0.4975  0.703 ]]

 f:
[0.3   0.359 0.733 0.735]


2 итерация:
 A:
 [[ 1.          0.17       -0.25        0.54      ]
 [ 0.          0.9201      0.7875     -0.5738    ]
 [ 0.          0.          0.65693512 -0.45066841]
 [ 0.          0.          0.20949462  0.91285078]]

 f:
[0.3        0.359      0.58914248 0.60370612]


3 итерация:
 A:
 [[ 1.          0.17       -0.25        0.54      ]
 [ 0.          0.9201      0.7875     -0.5738    ]
 [ 0.          0.          0.65693512 -0.45066841]
 [ 0.          0.          0.          1.05656757]]

 f:
[0.3        0.359      0.58914248 0.41583036]


Ответ:
 [ 0.44088855 -0.36303099  1.16679833  0.39356722]


In [28]:
np.testing.assert_allclose(np.linalg.solve(test_A1, test_f1),
                           gaussian_elimination(test_A1, test_f1), atol=1)

Исходные данные:
 A:
 [[10. -7.  0.]
 [-3.  2.  6.]
 [ 5. -1.  5.]]

 f:
[7. 4. 6.]


1 итерация:
 A:
 [[10.  -7.   0. ]
 [ 0.  -0.1  6. ]
 [ 0.   2.5  5. ]]

 f:
[7.  6.1 2.5]


2 итерация:
 A:
 [[10.  -7.   0. ]
 [ 0.   2.5  5. ]
 [ 0.   0.   6.2]]

 f:
[7.  2.5 6.2]


Ответ:
 [ 0. -1.  1.]


In [29]:
np.testing.assert_allclose(np.linalg.solve(test_A2, test_f2),
                           gaussian_elimination(test_A2, test_f2))

Исходные данные:
 A:
 [[1. 2.]
 [3. 4.]]

 f:
[[3. 5.]
 [5. 9.]]


1 итерация:
 A:
 [[3.         4.        ]
 [0.         0.66666667]]

 f:
[[5.         9.        ]
 [1.33333333 2.        ]]


Ответ:
 [[-1. -1.]
 [ 2.  3.]]


In [30]:
np.testing.assert_allclose(np.linalg.solve(test_A3, test_f3),
                           gaussian_elimination(test_A3, test_f3))

Исходные данные:
 A:
 [[ 1.  1.  2.  3.]
 [ 1.  2.  3. -1.]
 [ 3. -1. -1. -2.]
 [ 2.  3. -1. -1.]]

 f:
[ 1. -4. -4. -6.]


1 итерация:
 A:
 [[ 3.         -1.         -1.         -2.        ]
 [ 0.          2.33333333  3.33333333 -0.33333333]
 [ 0.          1.33333333  2.33333333  3.66666667]
 [ 0.          3.66666667 -0.33333333  0.33333333]]

 f:
[-4.         -2.66666667  2.33333333 -3.33333333]


2 итерация:
 A:
 [[ 3.         -1.         -1.         -2.        ]
 [ 0.          3.66666667 -0.33333333  0.33333333]
 [ 0.          0.          2.45454545  3.54545455]
 [ 0.          0.          3.54545455 -0.54545455]]

 f:
[-4.         -3.33333333  3.54545455 -0.54545455]


3 итерация:
 A:
 [[ 3.         -1.         -1.         -2.        ]
 [ 0.          3.66666667 -0.33333333  0.33333333]
 [ 0.          0.          3.54545455 -0.54545455]
 [ 0.          0.          0.          3.92307692]]

 f:
[-4.         -3.33333333 -0.54545455  3.92307692]


Ответ:
 [-1. -1. -0.  1.]


In [31]:
np.testing.assert_allclose(np.linalg.solve(test_A4, test_f4),
                           gaussian_elimination(test_A4, test_f4))

Исходные данные:
 A:
 [[ 1. -2. -1.]
 [-3.  2.  2.]
 [ 3. -1. -2.]]

 f:
[[ 1.  0.]
 [ 2. -2.]
 [-3.  1.]]


1 итерация:
 A:
 [[-3.          2.          2.        ]
 [ 0.         -1.33333333 -0.33333333]
 [ 0.          1.          0.        ]]

 f:
[[ 2.         -2.        ]
 [ 1.66666667 -0.66666667]
 [-1.         -1.        ]]


2 итерация:
 A:
 [[-3.          2.          2.        ]
 [ 0.         -1.33333333 -0.33333333]
 [ 0.          0.         -0.25      ]]

 f:
[[ 2.         -2.        ]
 [ 1.66666667 -0.66666667]
 [ 0.25       -1.5       ]]


Ответ:
 [[-2.  4.]
 [-1. -1.]
 [-1.  6.]]
