In [5]:
import numpy as np

In [36]:
# Задаём матрицу A
b = np.matrix([[10, -7, 0], [-3, 2, 6], [5, -1, 5]], dtype=np.dtype(np.float32))
a = b.copy()
a

matrix([[10., -7.,  0.],
        [-3.,  2.,  6.],
        [ 5., -1.,  5.]], dtype=float32)

In [37]:
# Задаём столбец f
f = np.array([7, 4, 6], dtype=np.dtype(np.float32))
f

array([7., 4., 6.], dtype=float32)

In [38]:
# Итерации
for i in range(0, len(a)):
    print(i)

0
1
2


### 1 итерация 

In [39]:
# Берём первую колонку
first_col = a[0:, 0]
first_col

matrix([[10.],
        [-3.],
        [ 5.]], dtype=float32)

In [40]:
# Выбираем ведущий элемент
leading_elem = np.max(np.abs(first_col))
leading_elem

10.0

In [44]:
# Определяем нужно ли менять местами строки
i = 0 # Итерация
np.where(first_col == leading_elem)[0][0] != 0

False

In [12]:
coef = -(a[1, 0]/a[0, 0])

In [13]:
# 1.1 Домножим первое уравнение на 0.3 (-(-3/10))
a[1] = coef * a[0] + a[1]

In [14]:
f[1] = coef * f[0] + f[1]

In [15]:
coef = -(a[2, 0]/a[0, 0])

In [16]:
# 1.2 Домножим первое уравнение на -0.5 -(5/10)
a[2] = coef * a[0] + a[2]

In [17]:
f[2] = coef * f[0] + f[2]

In [18]:
a

matrix([[10.        , -7.        ,  0.        ],
        [ 0.        , -0.10000014,  6.        ],
        [ 0.        ,  2.5       ,  5.        ]], dtype=float32)

In [19]:
f

array([7.       , 6.1000004, 2.5      ], dtype=float32)

### 2 итерация

In [45]:
i = 1

In [46]:
# Берём вторую колонку
first_col = a[1:, 1]
first_col

matrix([[ 2.],
        [-1.]], dtype=float32)

In [47]:
# Выбираем ведущий элемент
leading_elem = np.max(np.abs(first_col))
leading_elem

2.0

In [48]:
# Определяем нужно ли менять местами строки
np.where(first_col == leading_elem)[0][0] != 0 # Нужно менять строку

False

In [24]:
k = len(a) - len(first_col)
max_col = first_col.argmax() + i

In [25]:
# Поменяли строки местами
a[[k, max_col]] = a[[max_col, k]]
f[[k, max_col]] = f[[max_col, k]]

In [26]:
coef = -(a[2, 1]/a[1, 1])
coef

0.04000006

In [27]:
# 1.1 Домножим второе уравнение на 0.04 (-(-0.1/2.5))
a[2] = coef * a[1] + a[2]

In [28]:
f[2] = coef * f[1] + f[2]

In [29]:
a

matrix([[10.       , -7.       ,  0.       ],
        [ 0.       ,  2.5      ,  5.       ],
        [ 0.       ,  0.       ,  6.2000003]], dtype=float32)

In [30]:
f

array([7.      , 2.5     , 6.200001], dtype=float32)

### Вычисляем X

In [31]:
x3 = np.round(f[-1]/a[-1, -1], 2)

In [32]:
x

NameError: name 'x' is not defined

In [ ]:
myA=[
 [1.0, -2.0, 3.0, -4.0],
 [3.0, 3.0, -5.0, -1.0],
 [3.0, 0.0, 3.0, -10.0],
 [-2.0, 1.0, 2.0, -3.0]
]

myB = [
 2.0,
 -3.0,
 8.0,
 5.0]
# --- end of исходные данные

# --- вывод системы на экран
def FancyPrint(A, B, selected):
    for row in range(len(B)):
        print("(", end='')
        for col in range(len(A[row])):
             print("\t{1:10.2f}{0}".format(" " if (selected is None
or selected != (row, col)) else "*", A[row][col]), end='')
        print("\t) * (\tX{0}) = (\t{1:10.2f})".format(row + 1, B[row]))
# --- end of вывод системы на экран

# --- перемена местами двух строк системы
def SwapRows(A, B, row1, row2):
    A[row1], A[row2] = A[row2], A[row1]
    B[row1], B[row2] = B[row2], B[row1]
# --- end of перемена местами двух строк системы

# --- деление строки системы на число
def DivideRow(A, B, row, divider):
    A[row] = [a / divider for a in A[row]]
    B[row] /= divider
# --- end of деление строки системы на число

# --- сложение строки системы с другой строкой, умноженной на число
def CombineRows(A, B, row, source_row, weight):
    A[row] = [(a + k * weight) for a, k in zip(A[row], A[source_row])]
    B[row] += B[source_row] * weight
# --- end of сложение строки системы с другой строкой, умноженной начисло

# --- решение системы методом Гаусса (приведением к треугольному виду)
def Gauss(A, B):
    column = 0
    while (column < len(B)):
        print("Ищем максимальный по модулю элемент в {0}-м столбце:".format(column + 1))
        current_row = None
        for r in range(column, len(A)):
            if current_row is None or abs(A[r][column]) > abs(A[current_row][column]):
                 current_row = r
        if current_row is None:
            print("решений нет")
            return None
        FancyPrint(A, B, (current_row, column))
        if current_row != column:
            print("Переставляем строку с найденным элементом повыше:")
            SwapRows(A, B, current_row, column)
            FancyPrint(A, B, (column, column))
        print("Нормализуем строку с найденным элементом:")
        DivideRow(A, B, column, A[column][column])
        FancyPrint(A, B, (column, column))
        print("Обрабатываем нижележащие строки:")
        for r in range(column + 1, len(A)):
            CombineRows(A, B, r, column, -A[r][column])
        FancyPrint(A, B, (column, column))
        column += 1
    print("Матрица приведена к треугольному виду, считаем решение")
    X = [0 for b in B]
    for i in range(len(B) - 1, -1, -1):
        X[i] = B[i] - sum(x * a for x, a in zip(X[(i + 1):], A[i][(i + 1):]))
    print("Получили ответ:")
    print("\n".join("X{0} =\t{1:10.2f}".format(i + 1, x) for i, x in
enumerate(X)))
    return X
# --- end of решение системы методом Гаусса (приведением к треугольному виду)
print("Исходная система:")
FancyPrint(myA, myB, None)
print("Решаем:")
Gauss(myA, myB)

In [ ]:
for i in range(len(B) - 1, -1, -1):
    X[i] = B[i] - sum(x * a for x, a in zip(X[(i + 1):], A[i][(i + 1):]))

In [ ]:
for i in range(10, -1, -1):
    print(i)