# QR-алгоритм со сдвигами

## Импорт модулей

In [153]:
import numpy as np        # для работы с матрицами и веторами
import warnings           # для работы с ошибками
import sympy as sp        # для красивого вывода промежуточных результатов
from IPython.display import Markdown, display  # для красивого вывода текста

## Входные данные

In [54]:
A = np.matrix([[4.33, -1.12, -1.08, 1.14],
               [-1.12, 4.33, 0.24, -1.22],
               [-1.08, 0.24, 7.21, -3.22],
               [1.14, -1.22, -3.22, 5.43]],
               dtype=np.dtype(np.float64))

In [141]:
A2 = np.matrix([[1.00, 0.42, 0.54, 0.66],
               [0.42, 1.00, 0.32, 0.44],
               [0.54, 0.32, 1.00, 0.22],
               [0.66, 0.44, 0.22, 1.00]],
               dtype=np.dtype(np.float64))

## Модифицированный алгоритм Грама-Шмидта для нахождения QR-разложения

In [142]:
def qr_mod_gram_schmidt(A_arg):
    A = np.copy(A_arg)
    n, m = A.shape
    R, Q = np.zeros(A.shape), np.zeros(A.shape)
    for k in range(n):
        s = 0
        for j in range(m):
            s += A[j, k]**2
            R[k, k] = np.sqrt(s)
        for j in range(m): Q[j, k] = A[j, k]/R[k, k]
        for i in range(k, n):
            s = 0
            for j in range(m):
                s += A[j, i] * Q[j, k]
                R[k, i] = s
            for j in range(m): A[j, i] = A[j, i] - R[k, i] * Q[j, k]
    return np.asmatrix(Q), np.asmatrix(R)

## QR-алгоритм

In [150]:
def qr_mod_algorithm(A: np.matrix, Kmax: int, delta) -> np.array:
    Ak = A
    t = 0
    I = np.identity(A.shape[0])
    eigvals = []
    d = delta
    k = 0
    while k < Kmax and d <= delta:
        Q, R = qr_mod_gram_schmidt(A - t * I)
        Ak = np.matmul(R,Q) + t * I if k else np.matmul(R, Q)
        t = Ak[-1, -1]
        eigvals.append(np.diagonal(Ak))
        d = np.linalg.norm(eigvals[-1] - eigvals[-2]) if k > 2 else delta
        k += 1
    return eigvals[-1]

## Результаты

In [151]:
real_res = qr_mod_algorithm(A, 20, 10**-10)
np_res = np.linalg.eigvals(A)
r = np_res - real_res
print(f"{real_res}\n{np_res}\n{r}")

[8.68343466 4.40539375 5.67714926 2.53402232]
[10.32677864  5.10251996  3.33893806  2.53176334]
[ 1.64334398e+00  6.97126206e-01 -2.33821121e+00 -2.25897359e-03]


In [152]:
real_res = qr_mod_algorithm(A2, 20, 10**-10)
np_res = np.linalg.eigvals(A2)
r = np_res - real_res
print(f"{real_res}\n{np_res}\n{r}")

[2.29623048 0.6804764  0.78102534 0.24226778]
[2.3227488  0.24226071 0.6382838  0.79670669]
[ 0.02651832 -0.43821569 -0.14274154  0.55443891]
