In [1]:
import numpy as np
import matplotlib.pyplot as plt
from typing import List

%matplotlib inline

In [2]:
L = 1
dX = 0.1
dT = 0.01
l = 0.5
C = 1
p = 0.8
a = np.sqrt(l/(C*p))
m = 10
T0 = 0
T1 = 0

In [39]:
def heat_equation(L=1, dX=0.1, dT=0.01, l=0.5, C=1, p=0.8, *, m=6, T0=0, T1=0) -> List[List[float]]:
    """ Метод сеток для решения уравнения теплопроводности
        
        :param L: длина стержня
        :type L: float
        :param dX: длина шага по оси X
        :type dX: float
        :param dT: длина шага по оси T
        :type dT: float
        :param l: коэффициент теплопроводности
        :type l: float
        :param C: удельная теплоёмкость
        :type C: float
        :param p: плотность материала стержня
        :type p: float
        :param m: количество кривых (с выбранным шагом dT)
        :type m: int
        :param T0: постоянная температура в начале стержня
        :type T0: float
        :param T1: постоянная температура на конце стержня
        :type T1: float
        
        :return: матрица, в которой показано решение уравнения теплопроводности
        :rtype: List[List[float]]
    """
    n = int(L/dX) + 1
    a = np.sqrt(l/(C*p))
    coef1 = 1-(2*a**2*dT/dX**2)
    coef2 = a**2*dT/dX**2
    u = np.zeros((n,m))
    u[0,:] = T0
    u[n-1,:] = T1
    for x in range(1, n-1):
        u[x,0] = 100*x*dX*(1-x*dX)
    for t in range(1, m):
        for x in range(1, n-1):
            u[x,t] = u[x,t-1]*coef1+coef2*(u[x+1,t-1]+u[x-1,t-1])
    return u

In [49]:
heat_equation()[:,0]

array([ 0.,  9., 16., 21., 24., 25., 24., 21., 16.,  9.,  0.])

In [41]:
heat_equation()[:,1]

array([ 0.  ,  7.75, 14.75, 19.75, 22.75, 23.75, 22.75, 19.75, 14.75,
        7.75,  0.  ])

In [47]:
heat_equation()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 9.        ,  7.75      ,  7.28125   ,  6.6171875 ,  6.30712891,
         5.75598145],
       [16.        , 14.75      , 13.5       , 12.73828125, 11.73242188,
        11.19958496],
       [21.        , 19.75      , 18.5       , 17.25      , 16.30517578,
        15.13146973],
       [24.        , 22.75      , 21.5       , 20.25      , 19.        ,
        17.94073486],
       [25.        , 23.75      , 22.5       , 21.25      , 20.        ,
        18.75      ],
       [24.        , 22.75      , 21.5       , 20.25      , 19.        ,
        17.94073486],
       [21.        , 19.75      , 18.5       , 17.25      , 16.30517578,
        15.13146973],
       [16.        , 14.75      , 13.5       , 12.73828125, 11.73242187,
        11.19958496],
       [ 9.        ,  7.75      ,  7.28125   ,  6.6171875 ,  6.30712891,
         5.75598145],
       [ 0.        ,  0.        ,  0.        ,  0.

In [46]:
heat_equation()[:,5]

array([ 0.        ,  5.75598145, 11.19958496, 15.13146973, 17.94073486,
       18.75      , 17.94073486, 15.13146973, 11.19958496,  5.75598145,
        0.        ])

In [36]:
def heat_equation1(L=1, dX=0.1, dT=0.01, l=0.5, C=1, p=0.8, *, m=6, T0=0, T1=0) -> List[List[float]]:
    """ Метод сеток для решения уравнения теплопроводности
        
        :param L: длина стержня
        :type L: float
        :param dX: длина шага по оси X
        :type dX: float
        :param dT: длина шага по оси T
        :type dT: float
        :param l: коэффициент теплопроводности
        :type l: float
        :param C: удельная теплоёмкость
        :type C: float
        :param p: плотность материала стержня
        :type p: float
        :param m: количество кривых (с выбранным шагом dT)
        :type m: int
        :param T0: постоянная температура в начале стержня
        :type T0: float
        :param T1: постоянная температура на конце стержня
        :type T1: float
        
        :return: матрица, в которой показано решение уравнения теплопроводности
        :rtype: List[List[float]]
    """
    n = int(L/dX) + 1
    a = np.sqrt(l/(C*p))
    coef1 = 1+(2*a**2*dT/dX**2)
    coef2 = a**2*dT/dX**2
    u = np.zeros((n,m))
    u[0,:] = T0
    u[n-1,:] = T1
    for x in range(1, n-1):
        u[x,0] = 100*x*dX*(1-x*dX)
    for t in range(m, 1):
        for x in range(1, n-1):
            u[x,t] = u[x,t+1]*coef1-coef2*(u[x+1,t+1]+u[x-1,t+1])
    return u

In [37]:
heat_equation1()[:,0]

array([ 0.,  9., 16., 21., 24., 25., 24., 21., 16.,  9.,  0.])

In [38]:
heat_equation1()[:,1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
heat_equation1()

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 9.,  0.,  0.,  0.,  0.,  0.],
       [16.,  0.,  0.,  0.,  0.,  0.],
       [21.,  0.,  0.,  0.,  0.,  0.],
       [24.,  0.,  0.,  0.,  0.,  0.],
       [25.,  0.,  0.,  0.,  0.,  0.],
       [24.,  0.,  0.,  0.,  0.,  0.],
       [21.,  0.,  0.,  0.,  0.,  0.],
       [16.,  0.,  0.,  0.,  0.,  0.],
       [ 9.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])